[env:esp32]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps =
	https://github.com/tzapu/WiFiManager.git
	https://github.com/bblanchon/ArduinoJson.git
	https://github.com/ArduinoGetStarted/button.git
	https://github.com/GyverLibs/FastBot.git
board_build.partitions = no_ota.csv