name: Build ESP32 Firmware

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install platformio

      - name: Build firmware
        run: |
          platformio run

      - name: Upload firmware as artifact
        uses: actions/upload-artifact@v2
        with:
          name: esp32-firmware
          path: |
            .pio/build/esp32/firmware.bin